### ISSUE TITLE
[BUG] Load video file if flac audio in mp4

### ISSUE THREAD

**Issue by narumi147** [jakky1/video_player_win#10]
~~After update to flutter 3.10~~ No related to flutter 3.10
video player always failed to load video file.
`VideoPlayerController.initialize` didn't throw the error, the win plugin only printed
```
[video_player_win] load fail, reload now
[log] [video_player_win] playback event: error
``` 

Since the error is not thrown, the app will treat it as initiated and playing(though it is errored). when calling `pause`. it will throw
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): video file not opened yet
#0      WinVideoPlayerController.pause         video_player_win.dart:200
#1      WindowsVideoPlayer.pause               video_player_win_plugin.dart:77
#2      VideoPlayerController._applyPlayPause  video_player.dart:555
#3      VideoPlayerController.pause            video_player.dart:516
```

Maybe errored before 3.10

**Comment by jakky1** [comment]
I test on 3.10 now, and it works well for me.

Could you tell me which video file / url you are playing?

**Comment by jakky1** [comment]
To clarify, some (and I think almost) video files are playable with this package.
Only some video files play failed.

Unfortunately, the video file you provided play failed with this package,
although I know Window Media Player can play it.

I also tried the Microsoft official sample code [topoedit](https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/multimedia/mediafoundation/topoedit) & [protectedplayback](https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/multimedia/mediafoundation/protectedplayback),
which are use Microsoft Media Foundation topology API too,
they also cannot play the video file you provided,
but can play my other video files well.

Since the above 2 official Microsoft samples play failed too,
so I have no idea how to solve this issue... orz

**Comment by jakky1** [comment]
About FLAC format,
I tried [these flac file](https://samples-files.com/sample-flac-files/),
and this package can play them.

So I think the FLAC format is supported if K-lite codec installed.

I also tried to ignore any audio tracks, and this package can play the file you provided. 
(of course only video, no audio)

Your video file maybe has some unusual data,
and the codec just cannot handle it.
But this cannot explain why Windows Media Player can play it...
(but official Microsoft sample code cannot play it, mentioned before)


About the error handling improvement you asked,
because the codec doesn't report error in normal way,
so I cannot do as your wish.

Why I print ``load fail, reload now``,
because when playing a video successfully,
there are many state-change occurs in ``MyPlayer::Invoke`` method,
but when playing your video file, or when playing network url failed if socket timeout,
the state-change acts in a different way, so I will reload it.
But I cannot distinguish them, so I cannot just report error to user.
And if codec cannot parse file successfully,
it should return false in ``BeginCreateObjectFromURL`` and in its callback, but it didn't in your video file.
So currently I won't change the code.

**Comment by annd22** [comment]
is there any update on this?

**Comment by jakky1** [comment]
@annd22,
`narumi147` has pointed out the following 2 questions:

** flac audio not support 
K-lite codec pack support it, and he has clarified that he not installed K-lite codec pack so load failed (May 14, 2023 post)

** WinVideoPlayerValue.IsInitialized is not passed to VideoPlayerValue.IsInitialized
I just test it 1 minute ago and it works fine.

**Comment by annd22** [comment]
`** WinVideoPlayerValue.IsInitialized is not passed to VideoPlayerValue.IsInitialized` I think this is not correct.

At the file `video_player_win.dart`, case 7, I have to fork the project and modify:
```case 7: // MEError
        log("[video_player_win] playback event: error");
        value = value.copyWith(
            isInitialized: false, hasError: true, isPlaying: false);
       // <-- add event to update isInitialized to false
        _eventStreamController.add(VideoEvent(
          eventType: VideoEventType.initialized, duration: null, size: null));
        _cancelTrackingPosition();
        break;```
        
Without the modified code, the value of isInitialized don't updated.

**Comment by jakky1** [comment]
@annd22,
Thanks for the code patch.

I try to fix it and upload to github.
Please try it and let me know if it works in your case.
```
dependencies:
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: master
```
