### ISSUE TITLE
Video sometimes don't play when starting more than one video at once 

### ISSUE THREAD

**Issue by hillelcoren** [jakky1/video_player_win#9]
Hi,

Thanks for the excellent package!

We've run into an issue when showing multiple video players on the screen at once, the setVolume function only affects the last video added.

**Comment by jakky1** [comment]
Hi,
From ``video_player_win``  version  2.2.0,
setVolume() only affects the specified VideoPlayerController.
( before 2.2.0, setVolume() affects all the other videos, but that's a bug, and fixed in 2.2.0 )

If you want to set all the volumes of video players, you need to set one by one.

**Comment by hillelcoren** [comment]
Thanks for the info, sorry for not first checking I was using the latest version.

It looks like I'm having trouble getting the app compile when using the latest version alongside the video_player_macos package.

`Resolving dependencies...
Because every version of video_player_macos depends on video_player_platform_interface ^5.1.1 and video_player_win >=1.1.6 depends on video_player_platform_interface ^6.0.1, video_player_macos is incompatible with video_player_win >=1.1.6.
So, because mudeo depends on both video_player_win ^2.2.0 and video_player_macos any, version solving failed.`

I'll follow up with the video_player_macos package.

**Comment by hillelcoren** [comment]
I found this issue: https://github.com/ollyde/flutter_macos_video_player/issues/14

Changing our pubspec to the following enabled it compile with the latest version:

```
video_player: ^2.5.3
video_player_win: ^2.2.0
video_player_macos:
  git:
    url: https://github.com/ollyde/flutter_macos_video_player.git
    path: packages/video_player/video_player_macos
```

However it seem like it's now actually worse. Before the videos would always play but there was the problem with setVolume whereas now many videos aren't able to play and no videos have sound. Any ideas?

**Comment by jakky1** [comment]
On which OS the issues you mentioned occurs?

If it occurs in Windows, could you please describe more details?
If it occurs in MacOS, since I have no Mac devices, so please contact the ``video_player_macos`` package owner.

**Comment by jakky1** [comment]
After ``video_player_win`` 2.2.0 (or 2.0.0),
yes sometimes video doesn't play if you start more than 2 videos simultaneously.

It is really a bug.
However, I'm focus on other project now, and I have no time to fix this in a short time :(
I'll try to fix it if I have time

Temp solution:
1. reload video manually if user see the video not play... XD
2. rollback to ``video_player_win: 1.1.6``, however the CPU usage may be high, depends on what you played and how many video you played simultaneously

**Comment by hillelcoren** [comment]
That probably explains it, the app is a multi-track video player/recorder so many videos are playing at once.

I'll update the issue title, thanks again!

**Comment by hillelcoren** [comment]
One thought, is it worth adding a parameter to optionally disable hardware acceleration until it's more stable?

**Comment by jakky1** [comment]
Fixed.
Only push to github

```
dependencies:
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: master
```

However, sometimes (3%) video not auto play (only display first frame), can call play() to fix

**Comment by hillelcoren** [comment]
It's a massive improvement, thank you!! 

3% would be fine but I'm seeing closer to 30% black screens. Calling stop/play does fix it though so there is a workaround when it happens.

**Comment by jakky1** [comment]
I think I found the root cause about video freeze (maybe)
I tried to open 100 times with each time open two 720p videos at the same time, and no video freeze at the beginning of 3 seconds.

I push to github only.
Please try it and  remember to    @``flutter pub get``@   to pull the latest version from github, and mark the temp solution you mentioned above first.

Hope this solution also works in your environment.

**Comment by hillelcoren** [comment]
There may be a small improvement however the app still works much better if I include the code above to start/stop/start the videos. Thanks again for your help with this!

**Comment by jakky1** [comment]
Hi,
I just push ``video_player_win: ^2.2.2`` to pub.dev
and maybe this version solve this issue.

I'll close this issue if no response in 7 days.

**Comment by hillelcoren** [comment]
Thanks! I'll give it a try...

**Comment by hillelcoren** [comment]
It keeps improving but I'm still seeing some errors, here are the logs. Note: in some cases our app can play up to 5 videos at once.

```
flutter: #0      WinVideoPlayerController.pause
#1      WindowsVideoPlayer.pause
#2      VideoPlayerController._applyPlayPause
#3      VideoPlayerController.pause
#4      VideoControllerCollection.play
#5      _SongListItemState._playVideos
#6      _SongListItemState._onVisibilityChanged
#7      RenderVisibilityDetectorBase._fireCallback
#8      RenderVisibilityDetectorBase._scheduleUpdate.<anonymous closure>
#9      RenderVisibilityDetectorBase._processCallbacks
#10     _TaskEntry.run.<anonymous closure>
#11     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#12     _TaskEntry.run
#13     SchedulerBinding.handleEventLoopCallback
#14     SchedulerBinding._runTasks
#15     _rootRun (dart:async/zone.dart:1390:47)
#16     _CustomZone.run (dart:async/zone.dart:1300:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#19     _rootRun (dart:async/zone.dart:1398:13)
#20     _CustomZone.run (dart:async/zone.dart:1300:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#25     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

flutter: #0      WinVideoPlayerController.seekTo
#1      WindowsVideoPlayer.seekTo
#2      VideoPlayerController.seekTo
#3      VideoControllerCollection.play
#4      _SongListItemState._playVideos
#5      _SongListItemState._onVisibilityChanged
#6      RenderVisibilityDetectorBase._fireCallback
#7      RenderVisibilityDetectorBase._scheduleUpdate.<anonymous closure>
#8      RenderVisibilityDetectorBase._processCallbacks
#9      _TaskEntry.run.<anonymous closure>
#10     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#11     _TaskEntry.run
#12     SchedulerBinding.handleEventLoopCallback
#13     SchedulerBinding._runTasks
#14     _rootRun (dart:async/zone.dart:1390:47)
#15     _CustomZone.run (dart:async/zone.dart:1300:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#18     _rootRun (dart:async/zone.dart:1398:13)
#19     _CustomZone.run (dart:async/zone.dart:1300:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#24     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

flutter: #0      WinVideoPlayerController.play
#1      WindowsVideoPlayer.play
#2      VideoPlayerController._applyPlayPause
#3      VideoPlayerController.play
#4      VideoControllerCollection.play.<anonymous closure>
#5      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
#6      _rootRun (dart:async/zone.dart:1390:47)
#7      _CustomZone.run (dart:async/zone.dart:1300:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#10     _rootRun (dart:async/zone.dart:1398:13)
#11     _CustomZone.run (dart:async/zone.dart:1300:19)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by jakky1** [comment]
Please try version v3.2.2. This version rewrites the entire underlying logic using the MediaEngine.
